# Generated by Django 5.2.5 on 2025-08-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_notification'),
        ('courses', '0002_simplify_course_image_field'),
    ]

    operations = [
    ]
